jobs:
  integrate:
    name: Create React Native App and integrate React Native Admob
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - continue-on-error: true
      name: Install xmlstarlet
      run: brew install xmlstarlet
    - continue-on-error: true
      name: Install xcpretty
      run: gem install xcpretty
    - continue-on-error: true
      name: Configure Xcode
      run: sudo xcode-select --switch /Applications/Xcode_11.app
    - continue-on-error: true
      name: Install React Native CLI
      run: sudo npm install -g react-native-cli
    - continue-on-error: true
      name: Initialize React Native application
      run: react-native init ReactNativeAdMobExample
    - continue-on-error: true
      name: Add react-native-admob
      run: yarn add react-native-admob@next
      working-directory: ./ReactNativeAdMobExample
    - continue-on-error: true
      name: Configure Android Project
      run: "xml ed -L \\\n  -s /manifest/application -t elem -n meta-data \\\n  -i\
        \ /manifest/application/meta-data -t attr -n android:name -v \"com.google.android.gms.ads.APPLICATION_ID\"\
        \ \\\n  -i /manifest/application/meta-data -t attr -n android:value -v \"\
        ca-app-pub-3940256099942544~1458002511\" \\\n  ./android/app/src/main/AndroidManifest.xml\n"
      working-directory: ./ReactNativeAdMobExample
    - continue-on-error: true
      name: Configure iOS Project
      run: "cp ../../Example/ios/ExampleTests/ExampleTests.m ./ReactNativeAdMobExampleTests/ReactNativeAdMobExampleTests.m\n\
        sed -i -e '/target '\"'\"'ReactNativeAdMobExample'\"'\"' do/a\\\n  pod '\"\
        '\"'Google-Mobile-Ads-SDK'\"'\"'\n' Podfile\n/usr/libexec/PlistBuddy -c 'Add\
        \ :GADApplicationIdentifier string ca-app-pub-3940256099942544~1458002511'\
        \ \\\n  ReactNativeAdMobExample/Info.plist\npod install\n"
      working-directory: ./ReactNativeAdMobExample/ios
    - continue-on-error: true
      name: Update App.js
      run: cp ../Example/App.js ./App.js
      working-directory: ./ReactNativeAdMobExample
    - continue-on-error: true
      name: Start packager
      run: react-native start &
      working-directory: ./ReactNativeAdMobExample
    - continue-on-error: true
      name: Run iOS
      run: react-native run-ios --simulator "iPhone 11 Pro"
      working-directory: ./ReactNativeAdMobExample
    - continue-on-error: true
      name: Take screenshot after delay
      run: sleep 30 && xcrun simctl io booted screenshot screenshot.png
    - continue-on-error: true
      uses: actions/upload-artifact@master
      with:
        name: screenshot
        path: ./screenshot.png
    - continue-on-error: true
      name: Run iOS tests
      run: "set -o pipefail && xcodebuild \\\n  -workspace ReactNativeAdMobExample.xcworkspace\
        \ \\\n  -scheme ReactNativeAdMobExample \\\n  -sdk iphonesimulator \\\n  -destination\
        \ 'platform=iOS Simulator,name=iPhone 11 Pro' \\\n  test | xcpretty\n"
      working-directory: ./ReactNativeAdMobExample/ios
name: Integrate React Native AdMob
on:
  repository_dispatch:
    types: trigger-ga___integrate.yml
